version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_apache_php
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile_mysql
    hostname: mysql  
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw # Change this to your desired MySQL root password
      MYSQL_DATABASE: mydatabase # Change this to your desired database name
