# Use the official MySQL image
FROM mysql:5.7

# Set MySQL root password (change to your own password)
ENV MYSQL_ROOT_PASSWORD=my-secret-pw

# Copy the init.sql script to the docker-entrypoint-initdb.d directory
COPY init.sql /docker-entrypoint-initdb.d/

# Expose the port MySQL runs on (default is 3306)
EXPOSE 3306
